log:
  level: info

runner:
  file: .runner
  capacity: 2
  env_file: .env
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  labels:
    - ubuntu-latest:docker://gitea/runner-images:ubuntu-latest
    - ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04
    - ubuntu-20.04:docker://gitea/runner-images:ubuntu-20.04
    - rocky-minimal:docker://aborys/podman-builder:latest-rocky-minimal
    - rocky:docker://aborys/podman-builder:latest-rocky

cache:
  enabled: true
  dir: ""
  host: ""
  port: 0
  external_server: ""

container:
  network: ""
  privileged: false
  options: --security-opt label=disable --security-opt seccomp=unconfined --device /dev/fuse:rw
  workdir_parent:
  valid_volumes: []
  docker_host: ""
  force_pull: false
  force_rebuild: false

host:
  workdir_parent:
