# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  push:
    tags:
      - "**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        flavor: [rocky, rocky-minimal, fedora]
    runs-on: rocky-minimal

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Echo git ref
        run: echo ${{ gitea.ref_name }}

      - name: Build ${{ matrix.flavor }} image
        id: build-image-rocky
        uses: redhat-actions/buildah-build@v2
        with:
          image: podman-builder
          tags: latest-${{ matrix.flavor }} ${{ github.sha }}-${{ matrix.flavor }}
          containerfiles: |
            ./Containerfile.${{ matrix.flavor }}
